### ISSUE TITLE
报错信息

### ISSUE THREAD

**Issue by xie0227** [jjeejj/geektime2pdf#11]
这种报错怎么办啊
`
$ node columnArticleList.js
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'superagent'

`

**Comment by AkaneMurakawa** [comment]
@xie0227 缺少模块，试着换一下npm镜像，下载所需的依赖模板

**Comment by xie0227** [comment]
> @xie0227 缺少模块，试着换一下npm镜像，下载所需的依赖模板

感谢已经可以运行了但是运行完成后得到的文件夹只有一个articleInfoList.json,而且好像只有第一篇文章的内容，我cookie用的文章第一章的是这个原因吗，如果是的话我是不是需要将cookie转化成登陆完成极客时间的主界面的cookie

**Comment by xie0227** [comment]
切换了镜像

> @xie0227 缺少模块，试着换一下npm镜像，下载所需的依赖模板

(node:18336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). To termin
ate the node process on unhandled promise rejection, use the CLI flag `--unhandl
ed-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejecti
ons_mode). (rejection id: 2)
爬取到11章的时候显示了这个错误

**Comment by jjeejj** [comment]
> 
> 
> 切换了镜像
> 
> > @xie0227 缺少模块，试着换一下npm镜像，下载所需的依赖模板
> 
> (node:18336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
> error originated either by throwing inside of an async function without a catch
> block, or by rejecting a promise which was not handled with .catch(). To termin
> ate the node process on unhandled promise rejection, use the CLI flag `--unhandl ed-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejecti
> ons_mode). (rejection id: 2)
> 爬取到11章的时候显示了这个错误

重新爬取，或者把之前的node_mudole删除在重新安装，执行
