### ISSUE TITLE
作者大佬可以帮忙看看拉钩教育能不能做成类似的导出吗？

### ISSUE THREAD

**Issue by lichangao1826** [jjeejj/geektime2pdf#13]
![image](https://user-images.githubusercontent.com/27681141/78589254-81f2cf80-7872-11ea-9b9e-13c1a370cdc5.png)

**Comment by lichangao1826** [comment]
我根据作者的代码实现了一下，需要的自取：https://github.com/lichangao1826/lagou2pdf
请问作者 article.ejs 的生成有什么好的方法吗？我导出pdf之后发现还有一些样式缺失，希望作者可以帮忙看看 @jjeejj

**Comment by jjeejj** [comment]
@lichangao1826  article.ejs 的生成：把你看到网页另存为下来，然后在用浏览器打开你本地存下来的网页，查看是否是完整的
