### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by shtest1991** [jjeejj/geektime2pdf#16]
MacBook-Pro:geektime2pdf stonetest$ node columnArticleList.js 

该文件夹已经存在 /Users/stonetest/geektime2pdf/geektime_MySQL实战45讲

专栏文章链接开始获取

error msg 用户未购买此专栏

访问 地址 https://time.geekbang.org/column/article/78427 err 用户未购买此专栏

专栏文章链接获取完成

**

 * 需要转换为 pdf 的配置信息 

 */

module.exports = {

    url: 'https://time.geekbang.org/serv/v1/article',

    commentUrl: 'https://time.geekbang.org/serv/v1/comments',

    columnBaseUrl: 'https://time.geekbang.org/column/article/',

    columnName: 'MySQL实战45讲',

    firstArticalId: 78427, //专栏第一篇文章的ID

    isdownloadVideo: false, // 是否下载音频

    isComment: true, // 是否导出评论

    cookie: '_ga=GA1.2.2063249228.1573724722;GCID=bfdb8a9-972b001-95b8360-8a40fc6; GRID=bfdb8a9-972b001-95b8360-8a40fc6; _gid=GA1.2.1892212275.1587371465;  _gat=1; SERVERID=1fa1f330efedec1559b3abbcb6e30f50|1587537595|1587535691; Hm_lvt_022f847c4e3acd44d4a2481d9187f1e6=1587536660,1587536666,1587537528,1587537551; Hm_lpvt_022f847c4e3acd44d4a2481d9187f1e6=1587537594; GCESS=BAcEUpJfGQIEjeafXgQEAC8NAAoEAAAAAAwBAQsC

**Comment by jjeejj** [comment]
@shtest1991 这个是下载自己已经购买的专栏

**Comment by ghost** [comment]
是的， 这个专栏我已经购买了的。

**Comment by jjeejj** [comment]
检查一下 你的 cookie 是否有问题
