### ISSUE TITLE
已经购买了专栏，但是不能下载

### ISSUE THREAD

**Issue by AXinsLab** [jjeejj/geektime2pdf#18]
已经购买了专栏，也确定在浏览器登录了帐号，
如果通过firstArticalId配置专栏，就只能下载免费阅读的那一篇文章，之后没有任何提示 ; 
如果通过articalIds进行手动配置则同样只能下载第一篇文章，之后显示访问：
    访问 地址  https://time.geekbang.org/column/article/186076 err 用户未购买此专栏（确定已经购买）
希望大佬能看看

**Comment by jjeejj** [comment]
@grant-Gan  检查 cookie 是否设置正确了

**Comment by AXinsLab** [comment]
已经解决了，谢谢！！

**Comment by wangyu0361** [comment]
> 已经解决了，谢谢！！

请问您是如何解决的，能分享一下吗？
