### ISSUE TITLE
求助 error msg 用户未购买此专栏

### ISSUE THREAD

**Issue by NikoliaWong** [jjeejj/geektime2pdf#23]
已经有阅读权限，但是下载的时候还是报错
error msg 用户未购买此专栏。

**Comment by jjeejj** [comment]
已经购买专栏了吗？ 如果购买专栏了，确定 cookie 是否使用正确

**Comment by NikoliaWong** [comment]
购买了。cookie是用document.cookie获取后直接复制进去的

**Comment by NikoliaWong** [comment]
> 已经购买专栏了吗？ 如果购买专栏了，确定 cookie 是否使用正确

购买了。cookie是用document.cookie获取后直接复制进去的

**Comment by jjeejj** [comment]
可以参考这个 issue #21
