### ISSUE TITLE
只能得到一篇文章或者Cookie不合法的解决办法

### ISSUE THREAD

**Issue by csbo98** [jjeejj/geektime2pdf#30]

**Comment by csbo98** [comment]
在使用的时候，把articalIds设置为空列表，设置firstArticalId为专栏首篇文章的ID，运行程序仅仅能得到某个课程的第一篇文章的PDF，无法得到所有的PDF

**Comment by csbo98** [comment]
问题解决了，使用这个项目容易出错的地方是cookie比较难设置，实测Google和Edge两个浏览器的Cookie都不行，最好使用Firefox的cookie。。 注意是请求头中的cookie

**Comment by 0range1** [comment]
> 问题解决了，使用这个项目容易出错的地方是cookie比较难设置，实测Google和Edge两个浏览器的Cookie都不行，最好使用Firefox的cookie。。 注意是请求头中的cookie

使用了Firefox的cookie也不行 可能是什么原因呢
![image](https://user-images.githubusercontent.com/49051639/128214618-9900f75c-6e8c-49c5-a19b-e13779862814.png)

**Comment by MrChocol** [comment]
可以在F12找到请求[articles](https://time.geekbang.org/serv/v1/column/articles)的返回结果，提取里面的id，再把id放到配置里面去就可以了，cookie把请求头里面的Cookie考到配置文件里面来就ok了，导出非常easy

**Comment by csbo98** [comment]
你买课程了没有 不买不可以的&nbsp; 你的错误是什么呀






cslb
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jjeejj/geektime2pdf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月5日(星期四) 凌晨0:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jjeejj/geektime2pdf] 只能得到一篇文章或者Cookie不合法的解决办法 (#30)





  
问题解决了，使用这个项目容易出错的地方是cookie比较难设置，实测Google和Edge两个浏览器的Cookie都不行，最好使用Firefox的cookie。。 注意是请求头中的cookie
  
使用了Firefox的cookie也不行 可能是什么原因呢
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 0range1** [comment]
拷贝cookie的时候不小心把换行也拷贝了，已经解决了 感谢🙏
